# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(verbose_name=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Sucursales')),
            ],
        ),
        migrations.CreateModel(
            name='Suministros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now=True)),
                ('id_suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Sucursales')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='suministros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministros.Suministros'),
        ),
    ]
