# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0002_auto_20170111_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='id_suc',
            new_name='sucursal',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='suministros',
            new_name='articulo',
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipo',
            field=models.CharField(choices=[('oficina', 'Oficina'), ('limpieza', 'Limpieza')], default='oficina', max_length=50),
            preserve_default=False,
        ),
    ]
