# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0003_auto_20170111_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='sucursal',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='articulo',
            field=models.CharField(max_length=50),
        ),
    ]
