# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0005_articulos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
