# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Razones_Sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('grupo tenis show sa de cv', 'GRUPO TENIS SHOW SA DE CV'), ('elia daissa monarrez', 'ELIA DAISSA MONARREZ'), ('elia denisse monarrez', 'ELIA DENISSE MONARREZ'), ('hector ernesto monarrez palazuelos', 'HECTOR ERNESTO MONARREZ PALAZUELOS')], max_length=50)),
                ('rfc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('lacoste', 'Lacoste'), ('the body shop', 'The Body Shop'), ('benissimo', 'Benissimo'), ('tenis show', 'Tenis Show'), ('kenneth cole', 'Kenneth Cole')], max_length=80)),
                ('ciudad', models.CharField(choices=[('culiacan', 'Culiacan'), ('leon', 'Leon'), ('guadalajara', 'Guadalajara'), ('cabo san lucas', 'Cabo San Lucas')], max_length=80)),
                ('plaza', models.CharField(choices=[('san isidro', 'San Isidro'), ('walmart', 'Walmart'), ('forum', 'Forum'), ('galerias san miguel', 'Galerias San Miguel'), ('plaza fiesta', 'Plaza Fiesta'), ('puerto paraiso', 'Puerto Paraiso'), ('las plazas', 'Las Plazas Outlet'), ('outlet mulza', 'Outlet Mulza'), ('oficina', 'Oficina Mara')], max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=249)),
                ('domicilio', models.CharField(max_length=249)),
                ('rs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Razones_Sociales')),
            ],
        ),
    ]
