# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=50)),
                ('curp', models.CharField(max_length=50)),
                ('imss', models.CharField(max_length=50)),
                ('no_imss', models.CharField(max_length=50)),
                ('bod', models.DateField()),
                ('sexo', models.BooleanField(default=0)),
                ('ingreso', models.DateField(auto_now=True)),
                ('salida', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(choices=[(0, 'Mujer'), (1, 'Hombre')], default=1)),
                ('puesto', models.CharField(choices=[('recursos humanos', 'Recurso Humanos'), ('informatica', 'Informatica'), ('auxiliar de almacen', 'Auxiliar de almacen'), ('credito', 'Credito'), ('auxiliar administrativo', 'Auxiliar administrativo'), ('guardia', 'Guardia'), ('asesor', 'Asesor'), ('sublider', 'Sublider'), ('lider', 'Lider'), ('coordinar de operaciones', 'Coordinador de operaciones')], max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(max_length=249)),
                ('infonavit', models.CharField(max_length=150)),
                ('rfc', models.CharField(max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Sucursales')),
            ],
        ),
    ]
